import type { Metadata } from "next";
import { Grandstander } from "next/font/google";
import "./globals.css";

const grandstander = Grandstander({
  variable: "--font-grandstander",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grandstander.variable} font-main leading-[1.2] font-medium text-white antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
